spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/note_db
    username: eno
    password: 888888

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true